In [1]:
# import pandas

import pandas as pd

# import csv

df = pd.read_csv('raw_extraction.csv')

In [2]:
df

       file_name                                           raw_text
0   18067556.pdf  MASTER DATA MANAGER\nExperience\nMaster Data M...
1   18159866.pdf  SENIOR VICE PRESIDENT OF GLOBAL INFORMATION TE...
2   18176523.pdf  SENIOR INFORMATION TECHNOLOGY MANAGER\nExecuti...
3   18187364.pdf  INFORMATION TECHNOLOGY SPECIALIST INFORMATION ...
4   18301617.pdf  INFORMATION TECHNOLOGY MANAGER\nSummary\nSucce...
5   18752129.pdf  INFORMATION TECHNOLOGY ANALYST\nSummary\nTo pu...
6   19201175.pdf  INFORMATION TECHNOLOGY SPECIALIST\nSummary\n\n...
7   19796840.pdf  INFORMATION TECHNOLOGY AUDITOR\nSkills\nPeople...
8   19850482.pdf  SENIOR VP - INFORMATION TECHNOLOGY\nExecutive ...
9   20001721.pdf  INFORMATION TECHNOLOGY STUDENT\nCareer Overvie...
10  20024870.pdf  INFORMATION TECHNOLOGY (INTERNSHIP)\nSummary\n...
11  20237244.pdf  INFORMATION TECHNOLOGY SPECIALIST\nSummary\nIn...
12  20408458.pdf  INFORMATION TECHNOLOGY SUPPORT SPECIALISTNETWO...
13  20674668.pdf  INFORMATION TECHNOLOGY SPECIALIST III (DRUPAL ...
14  20824105.pdf  INFORMATION TECHNOLOGY AND AWS ADMIN INTERN\nE...
15  20879311.pdf  DIRECTOR OF INFORMATION TECHNOLOGY AND ANALYTI...
16  21283365.pdf  DIRECTOR OF INFORMATION TECHNOLOGY\nSummary\nI...
17  21780877.pdf  INFORMATION TECHNOLOGY SPECIALIST GS11\nExperi...
18  22450718.pdf  INFORMATION TECHNOLOGY SPECIALIST\nProfessiona...
19  22776912.pdf  DIRECTOR OF INFORMATION TECHNOLOGY /CHIEF TECH...
20  23527321.pdf  HEAD, INFORMATION TECHNOLOGY AND INFORMATION C...
21  23666211.pdf  TRAINING MANAGER\nExecutive Summary\n\nQualifi...
22  23864648.pdf  VICE PRESIDENT INFORMATION TECHNOLOGY INFRASTR...
23  24020470.pdf  INFORMATION TECHNOLOGY SPECIALIST\nSummary\n\n...
24  24038620.pdf  INFORMATION TECHNOLOGY DIRECTOR\nExperience\nI...
25  26994282.pdf  SALES\nProfessional Summary\nTalented Construc...
26  27233183.pdf  SALES ASSOCIATE\nSummary\nPunctual, customer-f...
27  27607632.pdf  SALES\nSummary\nSelf-motivated individual offe...
28  27624540.pdf  SALES ASSOCIATE/GOLF SALES ASSOCIATE\nExecutiv...
29  28139742.pdf  SALES ASSOCIATE\nSummary\nCustomer-focused man...
30  28198029.pdf  SALES ASSOCIATE\nSummary\n\nAssertive, outgoin...
31  28377361.pdf  SALES ASSOCIATE\nProfessional Summary\nFood se...
32  28867567.pdf  SALES REPRESENTATIVE-PSR\nSummary\n\nCustomer-...
33  29134721.pdf  SALES\nCareer Overview\n\nDuring the course of...
34  29184740.pdf  SALES\nCareer Focus\n\nSales and Marketing exp...
35  29211919.pdf  SALES ASSOCIATE\nSummary\n\nCourteous and depe...
36  29332616.pdf  SALES ASSOCIATE\nSummary\nServiceoriented empl...
37  29399491.pdf  SALES\nProfessional Summary\nI want a challeng...
38  29805310.pdf  SALES CLERK\nSummary\nConscientious, enthusias...
39  29815762.pdf  SALES ASSOCITE\nProfessional Summary\nDedicate...
40  29928796.pdf  SALES ASSOCIATE\nSummary\nAccountable Retail S...
41  30083943.pdf  SALES\nProfessional Summary\n\ngraduated from ...
42  30529547.pdf  SALES REPRESENTATIVE\nSummary\nBi-lingual,effi...
43  30608780.pdf  SALES\nCareer Focus\nProfessional, yet laid ba...
44  31199035.pdf  SALES ASSOCIATE\nSkill Highlights\n\nGreat abi...
45  31454430.pdf  SALES REPRESENTATIVE\nProfile\nAccomplished an...
46  32140087.pdf  SALES SUPPORT\nExperience\nSALES SUPPORT \nFeb...
47  33236701.pdf  SALES ASSOCIATE\nProfessional Profile\n  Relia...
48  33578873.pdf  SALES\nSummary\nI am looking for a career posi...
49  34131484.pdf  SALES ASSOCIATE\nSummary\n\nTo further my care...

In [3]:
# melihat null value
df.isnull().sum()

file_name    0
raw_text     0
dtype: int64

In [4]:
# menampilkan data yang kosong

df_null = df[df.isnull().any(axis=1)]

In [5]:
df_null

Empty DataFrame
Columns: [file_name, raw_text]
Index: []

In [6]:
# melihat 1 data kolom raw_text seluruhnya

sample_text = df['raw_text'][1]

In [7]:
sample_text

"SENIOR VICE PRESIDENT OF GLOBAL INFORMATION TECHNOLOGY\nExecutive Profile\n\nHigh-energy results oriented Chief Information Officer offering global professional experience in managing complex information technology\nenvironments and cross-cultural teams while effectively aligning and supporting key company initiatives.\n\nSkill Highlights\n\nStrategic Planning\nResults-Oriented\nSelf-Motivated\nCustomer-Oriented\n\nProject and Program Management\nChange Implementation\nTeam Leadership\nTime and Resources Optimization\n\nCore Accomplishments\n\nProject Management: Â \n\nManaged cross-functional teams on large implementations and development projects through out full cycles of system development and\nImplementation methodologies.\n\nÂ \n\nProject Planning: Â \n\nDeveloped successful implementation and migration project plans, providing and controlling detailed work-plans, data conversion and\nintegration strategies, and production cutover & contingency plans.\n\nSolutions Modeling: Â \n\nPerformed business requirements gathering, gap/fit analysis, solution designs, development and deployment of application solutions.\n\nTechnology Architecture: Â \n\nDesigned and implemented cutting-edge 24/7 technology infrastructure solutions, providing fail-over architecture and disaster recovery\nplans.\n\nDelivery Efficiency: Â \n\nDelivered all assigned projects on time and within budget, realizing significant improvement of processing efficiency through in-depth\nperformance analysis and process change.\n\nRisk Mitigation: Â \n\nConducted periodic risk assessments and mitigated risk by preparing and executing comprehensive testing strategies, which included\ncomplex business scenarios, and systematic stressed testing.\n\nCustomer Relations: Â \n\nDevelop and maintain all accounts referenceable, providing mutually beneficial partnerships between employers and customers.\n\nProfessional Experience\nSenior Vice President of Global Information Technology 06/2004 to Current Company Name City , State\n\nResponsible for all aspects of Information Technology globally with a staff of 70 employees world wide.\n\nDuring my first year tenure, eliminated high dependency on consulting firm supporting an ERP system globally by developing, hiring and\nmentoring adequate IT staff resulting in the creation of self-sufficiency and the generation of about of $2.5 million dollars savings per year.\n\nAs one of the key members of the M&A team, planned, and delivered successfully in all of the acquisitions executed by the company,\nenabling the realization of anticipated benefits through the migration of systems and integration of technology.\n\n\x0cDelivered a single global suite of applications with seamless integration that provided significant efficiency gains, by eliminating duplicity, and\nstreamlining business processes.\n\nIntroduced our Engineering and New Product Development teams to the use of Project Life Cycle management system speeding up our\nintroduction of new products to market\n\nEnabled effective analysis and decision making through improved analytical capabilities delivered in a single repository of reporting through\none data model across all entities.\n\nFormed the company's first IT Steering Committee which is utilized as the forum for IT strategic planning and priority recommendations\nregarding major IT projects.\n\nDeployed reliable, scalable and fault tolerant technical infrastructure that has provided maximum up time and redundancy on all mission\ncritical systems and technology\n\nProvided high-performance, high-availability and secured networks that are leveraged to facilitate voice, data and video communications\namong offices across the globe while generating significant cost savings.\n\nDirector of Information Technology 01/2002 to 06/2004 Company Name City , State\n\nManaged a large ERP implementation project and the technical infrastructure operations for a large replicator and distributor of DVD and\nVHS movies.\nResponsible for a staff of 20 IT professionals, directly involved in the implementation of new technology and business applications.\nCompleted successfully and on-time the implementation of Oracle applications, after taking over a project that was significantly late and full\nof issues.\nRestructured the technical infrastructure of the company to be able to support the new ERP system through out all US locations.\nLed the analysis, design and deployment of web applications to provide customers with access to real-time information and services.\nImplemented a wireless inventory control solution through the use of Radio Frequency devices.\nDeveloped a new technical support model and implemented new policies and procedures for the processing of technical support requests.\nHired and mentored new IT personnel for the post-production support of the new ERP application system.\nTrained overseas personnel on the implementation and configuration of Oracle applications.\n\nPractice Director 01/1995 to 01/2002 Company Name City , State\n\nManaged projects ranging from $500K to $10M, with an average budget savings of 20% under estimate and ahead of schedule.\nCoordinated, directed, and managed a practice of 22 consultants.\nPrepared Request for Proposals responses for large-scale implementation projects.\nPerformed full lifecycle project management and supervision of both permanent employees and contractors, domestic, and offshore.\nDuring my 7-year tenure at Oracle Corporation, participated in the business development of over $24M of new contracts.\nCompleted successfully, on time and on budget, several large-scale implementations of Oracle's ERP suite of applications for Fortune 100\nclients.\nConducted Functional and technical architecture assessments, providing customers with solution designs, implementation approach, and\nrecommendations.\nServed as subject matter expert for the Supply Chain, Manufacturing and Financial aspects of several different projects.\nManaged multi-national virtual teams, operating on one large project from several different locations, achieved project benchmarks ahead of\nschedule/under budget.\nWorked closely with the development organization on integrated testing of product releases and customer pilots of new product.\n\nInformation Systems Director 01/1993 to 01/1995 Company Name City , State\n\nManaged business applications and technical infrastructure operations, for a 2,800-employee manufacturing and distribution company.\nNegotiated contracts, directed long-range planning, prepared and monitored budgets up to $8M, and conducted ROI studies.\nResponsible for the implementation of Manufacturing and Financial systems domestic and overseas.\nResponsible for the planning and introduction on new business processes and technology infrastructure to support company's growth.\nSuccessfully completed the implementation of Oracle Financials, that resulted in the decrease of past due accounts and in the increase of\naccuracy and timeliness of financial reporting.\nSuccessfully concluded the implementation of manufacturing applications at facilities in Monterrey, Mex., resulting in the decrease of\nmanufacturing cycles and the increase of supply chain performance at corporate targeted levels.\n\nInformation Systems Director 01/1990 to 01/1993 Company Name City , State\n\nSupported corporate-wide projects in the selection, delivery and management of new technology.\nSupervised traditional department management functions including fiscal responsibility, resource management, project management, and\nadministrative detail As the Project Manager, successfully completed the implementation and integration of MAPICS, increasing company's\nup-sell capabilities, by enhancing Supply Chain Streamline.\nSuccessfully deployed new hardware and software architecture through out the company and reduced significantly the need for non-\n\n\x0cintegrated PC based systems.\nImplemented the use of Electronic Data Interchange with preferred business partners increasing customer service levels.\nImplemented the use of statistical performance measurements, allowing top management to monitor productivity, order fulfillment ratios,\ninventory accuracy and other productivity related targets.\n\nInformation Systems & Technology Manager 01/1985 to 01/1990 Company Name City , State\n\nFunctioned as the Information Technology Manager while orchestrating the proposal and selection of new computing technology and\nEnterprise Resources Planning systems application.\nSuccessfully completed the implementation of MANMAN MRPII application.\nDesigned, developed and implemented a Pull Material System to improve inventory control and KANBAN replenishment of critical material\nitems.\nDesigned, developed and implemented a Bar Code Labeling System to manage shipping and receiving of raw materials and finished product\nand to comply with customer standards.\n\nSenior Systems Analyst 01/1984 to 01/1985 Company Name City , State\n\nResponsible for the implementation of retail industry best practices and for the development of new distribution and replenishment systems.\nDesigned and implemented a multi-tier replenishment system, for a large chain of supermarkets.\nParticipated in the designed an implementation of pricing & promotion systems and a sales forecasting system.\n\nEducation\nB.S : Computer Science 1983 University of Texas at El Paso City , State\n\nComputer Science\n\nLanguages\nBilingual - Fully fluent in English and Spanish.\nSkills\n\nâ€¢Experienced in strategic planning and execution.\n\nâ€¢Considerable knowledge of business theory, business processes, management, budgeting, and business office operations.\n\nâ€¢Substantial exposure to data processing, hardware platforms, enterprise software applications, and outsourced systems, including cloud SaaS\nand IaaS\n\nâ€¢Excellent understanding of computer systems characteristics, features, and integration capabilities.\n\nâ€¢Experienced with systems design and development from business requirements analysis through to day-to-day management.\n\nâ€¢Proven experience in IT planning, organization, and development.\n\nâ€¢Excellent understanding of project management principles.\n\nâ€¢Constant focus on organization's goals and objectives.\n\nâ€¢Demonstrated ability to apply IT in solving business problems.\n\nâ€¢In-depth knowledge of applicable laws and regulations as they relate to IT.\n\nâ€¢Strong understanding of human resource management principles, practices, and procedures.\n\nâ€¢Proven leadership ability.\n\nâ€¢Ability to set and manage priorities judiciously."

In [8]:
"MASTER DATA MANAGER\nExperience\nMaster Data Manager , 01/2019 to Current \nCompany Name â€“ City , State \n\nAligning 100+ supply chain-related master data attributes to ensure the following guidelines are met:.\nData Stewardship - Appropriate business units and ownership established to validate appropriate values, definitions and impact\ndocumentation for all master data fields.\nData Quality - Applicable controls are set in conjecture with IT to ensure that a proactive approach is taken to new master data.\nAdditionally, RPA process planned for Phase 2 to automate structured data entry and maintenance.\nData Integrity/Data Warehousing - Structure business logic to ensure BOMs and other data relationships are both accessible and built as an\nasset for the business.\nAdditionally, a Data Sync SOP was established for GS1 standardization.\nReporting - Automate data quality reporting for executive staff to ensure 99.8% compliance is adhered to throughout the organization.\nAdditionally, provide ad-hoc tools for the business to leverage clean data cubes.\nData Governance Committee - Oversee executive strategy in institutional master data to commit to trusted, accurate, structured and\nmeaningful master data.\nEngaging applicable stakeholders to promote data governance, data architect, data stewardship and data security the data governance\ncommittee oversees the framework for complex supply chain manufacturing operations.\n\nDirector of Information Technology , 01/2017 to 01/2019 \nCompany Name â€“ City , State \n\nSupply Chain Management - Warehouse, 3PL, Food Services, Served as the corporate Project Manager, overseeing all implementations\n(WMS, ERP, QMS, CMMS, infrastructure).\nResponsibilities included progress reporting, budget control, task delegation, plan creation, vendor coordination, etc.\nDeveloped a range of documents and performed project selection tasks such as workflow process maps, system integration documents,\ninfrastructure topology, organizational policies, GDPR, UAT, gap analysis, best fit models and user training manuals.\nDeployed and managed BI products to leverage company-wide data for decisionmakers, proactive analysis, and real-time resource\nplanning.\nUtilizing SSRS/PowerBI to analyze sets of data across multiple databases, automate value-add reporting to 3PL clients, visualize KPIs thru\nthe organization, create workflows for document automation and create alerts for various business units.\nLaunched a high-performance data warehouses and virtual machines to store, integrate, analyze, and report on enterprise data.\nAn array of SSAS cubes were deployed to allow for end-user ad-hoc tabular reports.\nAdditionally, a complex network of interfaces between 6+ enterprise systems, 4 SQL databases, 1 Oracle database, and other enterprise\nsystems (file server, exchange, EDI, etc) was implemented to support the ETL process.\nExecuting infrastructure refresh for a 200,000 sqft industrial/production facility.\nThe deployment includes an array of 15 switches, 1,000 cable runs, racking, 100 AP, 300 cameras, NVRs, controllers, and creating floor\nplans and topology documents.\nControlled a $2MM IT budget, short-term and long-term strategies, and CapEx justification across the business.\nIncluding selecting and negotiating with vendors, promoting operational process improvement, instituting best practices, and developing IT\nroadmaps and strategic plans.\nOn track to reduce IT spend by $250K by renegotiating vendor contracts, consolidating cloud services, implementing automation tools and\nupgrading legacy systems.\nResponsible for a team of IT professionals and vendors assigned to all corporate and local office systems, including ERP, WMS, logistics\nsystems, data centers, servers and storage, PCs, mobile devices, BDR, telecom, and help desk.\nReduced IT service desk's response time and resolution time while increasing knowledge base and reducing reoccurring tickets by over\n50%.\nInformation Technology Governance & Steering Committee (ITGSC) - Reporting directly to the board of directors, the ITGSC provided\nstrategic direction in aligning IT projects to shareholder interest and long-term targets.\nWhile overseeing the committee the cross-functional team guided 12 business units across operations, sales, and manufacturing.\nAdditionally, the ITGSC aided in risk management, business continuity, and organizational SOPs.\nNatJan Solutions (Facility Management - Retail, Medical, Grocery Sectors.\n\nInformation Technology and Analytics Manager , 01/2014 to 01/2017 \n\nImplemented process within external ERP portal to monetize 1000's of vendors to generate lean revenue based on financial and operational\ndata analysis.\nThis program is estimated to bring in $325,000 in its first year, an 8% increase in margin.\nCreated ad-hoc and scheduled BI (PowerBI/SSRS) reports to visualize critical client metrics and reports, internal performance KPIs,\noperational resource planning, asset and revenue forecasting, P/L summaries, expense budgets, etc.\nSpearheaded national RFP bids of multi-million-dollar procurement deals with several Fortune 500 retail, medical, and education\ncompanies.\nTasks included sales analysis, margin analysis, multivariable pricing structures, vendor acquisition, developing process flow and establishing\nKPI reporting for clientele and internal use.\nDesigned ad-hoc SQL views, stored proceduresand reports to address company-wide data analysis and modeling.\n\n\x0cUtilized advanced VBA programming and automation software to manage two billing systems, saving an estimated $75,000 in Salary\nExpenses in 2015, translating to a 40% reduction in departmental spending.\nReported on a wide array of KPIs on operations, sales, accounting, and vendors via dashboard-style (BI/SSRS) reports for COO, CFO,\nVice President of Sales and Account Manager use.\nOverhauled all company technology from on-premise systems to an array of cloud solutions, including replacing hardware and migrating\nservers and databases, this renovation saves ~$108,000 per year and provides long-term scalability.\n\n01/2015 to 01/2017 \nCompany Name â€“ City , State \n\nCo-Founded indoor, hydroponic farming company in South Jersey.\nBringing a hyper-local product to the Camden and Philadelphia region HGF generated $100K in its first year via a strategic relationship with\nthe premier food management service in Philadelphia, local restaurants, farmer's markets, and Whole Foods retail chain.\nSales & Operations Planning (S&OP) - The S&OP team managed bi-directional interactions between sales, marketing, production, and\nfinance.\nS&OP committee oversaw finished goods inventory controls, marketing vs financial targets, raw material and supplier management, logistics\nand human capital planning.\nAdditionally, benchmarks for product mix, SKU management, and forecast vs demand vs actual alignment.\nOperations - Oversaw the general operations of the farm, including assigning day-to-day jobs, tracking yield results, establishing daily work\nschedules, and tracking transplanting/harvesting schedules.\nAutomation Systems - Implemented an array of sensors to control environmental and nutrient levels.\nUtilizing this data and automation systems we drove automated pH balancing, nutrient leveling, temperature control, ventilation systems, and\nestablished a strong exception-based manufacturing operation.\nFinance - Oversaw all aspects of the financial responsibilities including establishing a point of sales systems, P/L reports, budgeting for OpEx\nand CapEx schedules, coordinating with lenders, insurance institutions and annual tax reports.\nSOPs - Instituted standard operating procedures to ensure quality standards are maintained and product consistency is maintained.\n\nWork History\nMaster Data Manager , 01/2019 to Current \nCompany Name â€“ City , State \n\nAligning 100+ supply chain-related master data attributes to ensure the following guidelines are met:.\nData Stewardship - Appropriate business units and ownership established to validate appropriate values, definitions and impact\ndocumentation for all master data fields.\nData Quality - Applicable controls are set in conjecture with IT to ensure that a proactive approach is taken to new master data.\nAdditionally, RPA process planned for Phase 2 to automate structured data entry and maintenance.\nData Integrity/Data Warehousing - Structure business logic to ensure BOMs and other data relationships are both accessible and built as an\nasset for the business.\nAdditionally, a Data Sync SOP was established for GS1 standardization.\nReporting - Automate data quality reporting for executive staff to ensure 99.8% compliance is adhered to throughout the organization.\nAdditionally, provide ad-hoc tools for the business to leverage clean data cubes.\nData Governance Committee - Oversee executive strategy in institutional master data to commit to trusted, accurate, structured and\nmeaningful master data.\nEngaging applicable stakeholders to promote data governance, data architect, data stewardship and data security the data governance\ncommittee oversees the framework for complex supply chain manufacturing operations.\n\nDirector of Information Technology , 01/2017 to 01/2019 \nCompany Name â€“ City , State \n\nSupply Chain Management - Warehouse, 3PL, Food Services, Served as the corporate Project Manager, overseeing all implementations\n(WMS, ERP, QMS, CMMS, infrastructure).\nResponsibilities included progress reporting, budget control, task delegation, plan creation, vendor coordination, etc.\nDeveloped a range of documents and performed project selection tasks such as workflow process maps, system integration documents,\ninfrastructure topology, organizational policies, GDPR, UAT, gap analysis, best fit models and user training manuals.\nDeployed and managed BI products to leverage company-wide data for decisionmakers, proactive analysis, and real-time resource\nplanning.\nUtilizing SSRS/PowerBI to analyze sets of data across multiple databases, automate value-add reporting to 3PL clients, visualize KPIs thru\nthe organization, create workflows for document automation and create alerts for various business units.\nLaunched a high-performance data warehouses and virtual machines to store, integrate, analyze, and report on enterprise data.\nAn array of SSAS cubes were deployed to allow for end-user ad-hoc tabular reports.\nAdditionally, a complex network of interfaces between 6+ enterprise systems, 4 SQL databases, 1 Oracle database, and other enterprise\nsystems (file server, exchange, EDI, etc) was implemented to support the ETL process.\nExecuting infrastructure refresh for a 200,000 sqft industrial/production facility.\nThe deployment includes an array of 15 switches, 1,000 cable runs, racking, 100 AP, 300 cameras, NVRs, controllers, and creating floor\nplans and topology documents.\nControlled a $2MM IT budget, short-term and long-term strategies, and CapEx justification across the business.\n\n\x0cIncluding selecting and negotiating with vendors, promoting operational process improvement, instituting best practices, and developing IT\nroadmaps and strategic plans.\nOn track to reduce IT spend by $250K by renegotiating vendor contracts, consolidating cloud services, implementing automation tools and\nupgrading legacy systems.\nResponsible for a team of IT professionals and vendors assigned to all corporate and local office systems, including ERP, WMS, logistics\nsystems, data centers, servers and storage, PCs, mobile devices, BDR, telecom, and help desk.\nReduced IT service desk's response time and resolution time while increasing knowledge base and reducing reoccurring tickets by over\n50%.\nInformation Technology Governance & Steering Committee (ITGSC) - Reporting directly to the board of directors, the ITGSC provided\nstrategic direction in aligning IT projects to shareholder interest and long-term targets.\nWhile overseeing the committee the cross-functional team guided 12 business units across operations, sales, and manufacturing.\nAdditionally, the ITGSC aided in risk management, business continuity, and organizational SOPs.\nNatJan Solutions (Facility Management - Retail, Medical, Grocery Sectors.\n\nInformation Technology and Analytics Manager , 01/2014 to 01/2017 \n\nImplemented process within external ERP portal to monetize 1000's of vendors to generate lean revenue based on financial and operational\ndata analysis.\nThis program is estimated to bring in $325,000 in its first year, an 8% increase in margin.\nCreated ad-hoc and scheduled BI (PowerBI/SSRS) reports to visualize critical client metrics and reports, internal performance KPIs,\noperational resource planning, asset and revenue forecasting, P/L summaries, expense budgets, etc.\nSpearheaded national RFP bids of multi-million-dollar procurement deals with several Fortune 500 retail, medical, and education\ncompanies.\nTasks included sales analysis, margin analysis, multivariable pricing structures, vendor acquisition, developing process flow and establishing\nKPI reporting for clientele and internal use.\nDesigned ad-hoc SQL views, stored procedures and reports to address company-wide data analysis and modeling.\nUtilized advanced VBA programming and automation software to manage two billing systems, saving an estimated $75,000 in Salary\nExpenses in 2015, translating to a 40% reduction in departmental spending.\nReported on a wide array of KPIs on operations, sales, accounting, and vendors via dashboard-style (BI/SSRS) reports for COO, CFO,\nVice President of Sales and Account Manager use.\nOverhauled all company technology from on-premise systems to an array of cloud solutions, including replacing hardware and migrating\nservers and databases, this renovation saves ~$108,000 per year and provides long-term scalability.\n\n01/2015 to 01/2017 \nCompany Name â€“ City , State \n\nCo-Founded indoor, hydroponic farming company in South Jersey.\nBringing a hyper-local product to the Camden and Philadelphia region HGF generated $100K in its first year via a strategic relationship with\nthe premier food management service in Philadelphia, local restaurants, farmer's markets, and Whole Foods retail chain.\nSales & Operations Planning (S&OP) - The S&OP team managed bi-directional interactions between sales, marketing, production, and\nfinance.\nS&OP committee oversaw finished goods inventory controls, marketing vs financial targets, raw material and supplier management, logistics\nand human capital planning.\nAdditionally, benchmarks for product mix, SKU management, and forecast vs demand vs actual alignment.\nOperations - Oversaw the general operations of the farm, including assigning day-to-day jobs, tracking yield results, establishing daily work\nschedules, and tracking transplanting/harvesting schedules.\nAutomation Systems - Implemented an array of sensors to control environmental and nutrient levels.\nUtilizing this data and automation systems we drove automated pH balancing, nutrient leveling, temperature control, ventilation systems, and\nestablished a strong exception-based manufacturing operation.\nFinance - Oversawall aspects of the financial responsibilities including establishing a point of sales systems, P/L reports, budgeting for OpEx\nand CapEx schedules, coordinating with lenders, insurance institutions and annual tax reports.\nSOPs - Instituted standard operating procedures to ensure quality standards are maintained and product consistency is maintained.\n\nEducation\nBachelor of Science : Management of Information Systems , 2017 \nAssociates of Science : Accounting , 2015 \nRowan College \nPursuing Project Management Professional (PMP) certification Rowan University \nSummary\nZeel Patel is an Information Technology Manager with a focus on IT transformation and process improvement currently looking for opportunities in\nthe greater Miami, FL metropolitan area. Zeel has experience working with corporate data in the areas of data presentation, structured and\nunsecured datasets, data mining, statistical analysis, UI creation, data warehouse management, and assessing data quality. Additionally, Zeel's\ndiverse background has allowed him to succeed in a project management and IT management role. In this role, Zeel has engaged in holistic\nbusiness analysis, process improvement, strategic planning, budgeting, contract negotiations, vendor relations, resource management, instituting\nbest practices, and overseeing/implementing multiple enterprise systems (ERP, WMS, CRM, WOM, QMS, SCP).\nHighlights\n\nAutomation tools, HTML, Retail\n\n\x0cMicrosoft Office Suite with deep Office 365, Dynamics 365, Project, PowerApps, PowerBI,\nFlow,\nSharepoint, Excel, Access, Intune, Visio, EMS, and Azure proficiency\nProgramming/Databases: SQL (SSRS, SSIS, SSAS), VBA, DAX, HTML, CSS, VBA,\nVB.NET, R, Powershell, Python, Oracle\nBusiness Intelligence Packages: PowerBI, Qlik (QlikView/QlikSense), SiSense, Tableau,\nDatorama, Yellowfin, Crystal, SSRS\nStrong knowledge of AWS, Azure, Cisco Switch Management, VMWare, Hyper-V, RDP,\nAutomation Anywhere, Active Directory,\nAnd hardware and software administration for iOS, Android, Windows, Red Hat Linux, RF\ndevices\nVB.NET, EDI, Procurement, Ventilation\nAccounting, ERP, Programming, Visio\nActive Directory, ETL, Progress, VBA\nPremier, Facility Management, Project Management, Workflow\nAd, Finance, Python\nAP, Financial, Quality\nApproach, Floor plans, Real-time\nArchitect, Forecasting, Red Hat Linux\nAutomate, Functional, Renovation\nAutomation, Help desk, Reporting\n\nAutomation tools, HTML, Retail\nBilling systems, Information\nTechnology, RFP\nBudgeting, Insurance, Risk\nmanagement\nBudgets, Inventory, Sales\nBudget, Logic, Sales analysis\nBI, Logistics, Servers\nBusiness Intelligence, Marketing,\nSOP\nCable, Access, SQL\nCisco, Excel, Strategy\nHardware, Exchange, Strategic\nContracts, Microsoft Office Suite,\nStrategic plans\nCrystal, Office, Structured\nCSS, Sharepoint, Supplier\nmanagement\nClientele, Windows, Supply chain\nClient, Negotiating, Supply Chain\nManagement\nClients, Enterprise, Switches\nData analysis, Network, Switch\nData entry, Oracle, System\nintegration\nData analysis and modeling, Oracle\ndatabase, Tableau\nData warehouses, Organizational,\nTax\nDatabases, Cameras, User training\nData Warehousing, Policies,\nTelecom\nDirection, Pricing, Translating\nDocumentation, Process\nimprovement, Upgrading\n\nSkills\n\nMicrosoft Office Suite with deep Office 365, Dynamics 365, Project, PowerApps, PowerBI, Flow,\nSSharepoint, Excel, Access, Intune, Visio, EMS, and Azure proficiency\nPProgramming/Databases: SQL (SSRS, SSIS, SSAS), VBA, DAX, HTML, CSS, VBA, VB.NET, R, Powershell, Python, Oracle\nBBusiness Intelligence Packages: PowerBI, Qlik (QlikView/QlikSense), SiSense, Tableau, Datorama, Yellowfin, Crystal, SSRS\nSStrong knowledge of AWS, Azure, Cisco Switch Management, VMWare, Hyper-V, RDP, Automation Anywhere, Active Directory,\nAand hardware and software administration for iOS, Android, Windows, Red Hat Linux, RF devices,\nVB.NET, accounting, Active Directory, premier, ad, AP, approach, architect, Automate, Automation, automation tools, billing systems,\n\nbudgeting, budgets, budget, BI, Business Intelligence, cable, Cisco, hardware, contracts, Crystal, CSS, clientele, client, clients, data analysis, data\nentry, data analysis and modeling, data warehouses, Databases, Data Warehousing, direction, documentation, EDI, ERP, ETL, Facility\nManagement, Finance, financial, floor plans, forecasting, functional, help desk, HTML, Information Technology, insurance, inventory, logic,\nlogistics, marketing, Access, Excel, exchange, Microsoft Office Suite, Office, Sharepoint, Windows, negotiating, enterprise, network, Oracle,\nOracle database, organizational, cameras, policies, pricing, process improvement, procurement, Programming, progress, Project Management,\nPython, Quality, real-time, Red Hat Linux, renovation, reporting, Retail, RFP, risk management, Sales, sales analysis, servers, SOP, SQL,\nstrategy, strategic, strategic plans, structured, supplier management, supply chain, Supply Chain Management, switches, Switch, system integration,\nTableau, tax, user training, telecom, translating, upgrading, ventilation, Visio, VBA, workflow"

"MASTER DATA MANAGER\nExperience\nMaster Data Manager , 01/2019 to Current \nCompany Name â€“ City , State \n\nAligning 100+ supply chain-related master data attributes to ensure the following guidelines are met:.\nData Stewardship - Appropriate business units and ownership established to validate appropriate values, definitions and impact\ndocumentation for all master data fields.\nData Quality - Applicable controls are set in conjecture with IT to ensure that a proactive approach is taken to new master data.\nAdditionally, RPA process planned for Phase 2 to automate structured data entry and maintenance.\nData Integrity/Data Warehousing - Structure business logic to ensure BOMs and other data relationships are both accessible and built as an\nasset for the business.\nAdditionally, a Data Sync SOP was established for GS1 standardization.\nReporting - Automate data quality reporting for executive staff to ensure 99.8% compliance is adhered to throughout the organization.\nAdditionally, provide ad-hoc tools for the business to leverage clean data cubes.\nData Governance Committee - Oversee executive strategy in institutional master data to commit to trusted, accurate, structured and\nmeaningful master data.\nEngaging applicable stakeholders to promote data governance, data architect, data stewardship and data security the data governance\ncommittee oversees the framework for complex supply chain manufacturing operations.\n\nDirector of Information Technology , 01/2017 to 01/2019 \nCompany Name â€“ City , State \n\nSupply Chain Management - Warehouse, 3PL, Food Services, Served as the corporate Project Manager, overseeing all implementations\n(WMS, ERP, QMS, CMMS, infrastructure).\nResponsibilities included progress reporting, budget control, task delegation, plan creation, vendor coordination, etc.\nDeveloped a range of documents and performed project selection tasks such as workflow process maps, system integration documents,\ninfrastructure topology, organizational policies, GDPR, UAT, gap analysis, best fit models and user training manuals.\nDeployed and managed BI products to leverage company-wide data for decisionmakers, proactive analysis, and real-time resource\nplanning.\nUtilizing SSRS/PowerBI to analyze sets of data across multiple databases, automate value-add reporting to 3PL clients, visualize KPIs thru\nthe organization, create workflows for document automation and create alerts for various business units.\nLaunched a high-performance data warehouses and virtual machines to store, integrate, analyze, and report on enterprise data.\nAn array of SSAS cubes were deployed to allow for end-user ad-hoc tabular reports.\nAdditionally, a complex network of interfaces between 6+ enterprise systems, 4 SQL databases, 1 Oracle database, and other enterprise\nsystems (file server, exchange, EDI, etc) was implemented to support the ETL process.\nExecuting infrastructure refresh for a 200,000 sqft industrial/production facility.\nThe deployment includes an array of 15 switches, 1,000 cable runs, racking, 100 AP, 300 cameras, NVRs, controllers, and creating floor\nplans and topology documents.\nControlled a $2MM IT budget, short-term and long-term strategies, and CapEx justification across the business.\nIncluding selecting and negotiating with vendors, promoting operational process improvement, instituting best practices, and developing IT\nroadmaps and strategic plans.\nOn track to reduce IT spend by $250K by renegotiating vendor contracts, consolidating cloud services, implementing automation tools and\nupgrading legacy systems.\nResponsible for a team of IT professionals and vendors assigned to all corporate and local office systems, including ERP, WMS, logistics\nsystems, data centers, servers and storage, PCs, mobile devices, BDR, telecom, and help desk.\nReduced IT service desk's response time and resolution time while increasing knowledge base and reducing reoccurring tickets by over\n50%.\nInformation Technology Governance & Steering Committee (ITGSC) - Reporting directly to the board of directors, the ITGSC provided\nstrategic direction in aligning IT projects to shareholder interest and long-term targets.\nWhile overseeing the committee the cross-functional team guided 12 business units across operations, sales, and manufacturing.\nAdditionally, the ITGSC aided in risk management, business continuity, and organizational SOPs.\nNatJan Solutions (Facility Management - Retail, Medical, Grocery Sectors.\n\nInformation Technology and Analytics Manager , 01/2014 to 01/2017 \n\nImplemented process within external ERP portal to monetize 1000's of vendors to generate lean revenue based on financial and operational\ndata analysis.\nThis program is estimated to bring in $325,000 in its first year, an 8% increase in margin.\nCreated ad-hoc and scheduled BI (PowerBI/SSRS) reports to visualize critical client metrics and reports, internal performance KPIs,\noperational resource planning, asset and revenue forecasting, P/L summaries, expense budgets, etc.\nSpearheaded national RFP bids of multi-million-dollar procurement deals with several Fortune 500 retail, medical, and education\ncompanies.\nTasks included sales analysis, margin analysis, multivariable pricing structures, vendor acquisition, developing process flow and establishing\nKPI reporting for clientele and internal use.\nDesigned ad-hoc SQL views, stored proceduresand reports to address company-wide data analysis and modeling.\n\n\x0cUtilized advanced VBA programming and automation software to manage two billing systems, saving an estimated $75,000 in Salary\nExpenses in 2015, translating to a 40% reduction in departmental spending.\nReported on a wide array of KPIs on operations, sales, accounting, and vendors via dashboard-style (BI/SSRS) reports for COO, CFO,\nVice President of Sales and Account Manager use.\nOverhauled all company technology from on-premise systems to an array of cloud solutions, including replacing hardware and migrating\nservers and databases, this renovation saves ~$108,000 per year and provides long-term scalability.\n\n01/2015 to 01/2017 \nCompany Name â€“ City , State \n\nCo-Founded indoor, hydroponic farming company in South Jersey.\nBringing a hyper-local product to the Camden and Philadelphia region HGF generated $100K in its first year via a strategic relationship with\nthe premier food management service in Philadelphia, local restaurants, farmer's markets, and Whole Foods retail chain.\nSales & Operations Planning (S&OP) - The S&OP team managed bi-directional interactions between sales, marketing, production, and\nfinance.\nS&OP committee oversaw finished goods inventory controls, marketing vs financial targets, raw material and supplier management, logistics\nand human capital planning.\nAdditionally, benchmarks for product mix, SKU management, and forecast vs demand vs actual alignment.\nOperations - Oversaw the general operations of the farm, including assigning day-to-day jobs, tracking yield results, establishing daily work\nschedules, and tracking transplanting/harvesting schedules.\nAutomation Systems - Implemented an array of sensors to control environmental and nutrient levels.\nUtilizing this data and automation systems we drove automated pH balancing, nutrient leveling, temperature control, ventilation systems, and\nestablished a strong exception-based manufacturing operation.\nFinance - Oversaw all aspects of the financial responsibilities including establishing a point of sales systems, P/L reports, budgeting for OpEx\nand CapEx schedules, coordinating with lenders, insurance institutions and annual tax reports.\nSOPs - Instituted standard operating procedures to ensure quality standards are maintained and product consistency is maintained.\n\nWork History\nMaster Data Manager , 01/2019 to Current \nCompany Name â€“ City , State \n\nAligning 100+ supply chain-related master data attributes to ensure the following guidelines are met:.\nData Stewardship - Appropriate business units and ownership established to validate appropriate values, definitions and impact\ndocumentation for all master data fields.\nData Quality - Applicable controls are set in conjecture with IT to ensure that a proactive approach is taken to new master data.\nAdditionally, RPA process planned for Phase 2 to automate structured data entry and maintenance.\nData Integrity/Data Warehousing - Structure business logic to ensure BOMs and other data relationships are both accessible and built as an\nasset for the business.\nAdditionally, a Data Sync SOP was established for GS1 standardization.\nReporting - Automate data quality reporting for executive staff to ensure 99.8% compliance is adhered to throughout the organization.\nAdditionally, provide ad-hoc tools for the business to leverage clean data cubes.\nData Governance Committee - Oversee executive strategy in institutional master data to commit to trusted, accurate, structured and\nmeaningful master data.\nEngaging applicable stakeholders to promote data governance, data architect, data stewardship and data security the data governance\ncommittee oversees the framework for complex supply chain manufacturing operations.\n\nDirector of Information Technology , 01/2017 to 01/2019 \nCompany Name â€“ City , State \n\nSupply Chain Management - Warehouse, 3PL, Food Services, Served as the corporate Project Manager, overseeing all implementations\n(WMS, ERP, QMS, CMMS, infrastructure).\nResponsibilities included progress reporting, budget control, task delegation, plan creation, vendor coordination, etc.\nDeveloped a range of documents and performed project selection tasks such as workflow process maps, system integration documents,\ninfrastructure topology, organizational policies, GDPR, UAT, gap analysis, best fit models and user training manuals.\nDeployed and managed BI products to leverage company-wide data for decisionmakers, proactive analysis, and real-time resource\nplanning.\nUtilizing SSRS/PowerBI to analyze sets of data across multiple databases, automate value-add reporting to 3PL clients, visualize KPIs thru\nthe organization, create workflows for document automation and create alerts for various business units.\nLaunched a high-performance data warehouses and virtual machines to store, integrate, analyze, and report on enterprise data.\nAn array of SSAS cubes were deployed to allow for end-user ad-hoc tabular reports.\nAdditionally, a complex network of interfaces between 6+ enterprise systems, 4 SQL databases, 1 Oracle database, and other enterprise\nsystems (file server, exchange, EDI, etc) was implemented to support the ETL process.\nExecuting infrastructure refresh for a 200,000 sqft industrial/production facility.\nThe deployment includes an array of 15 switches, 1,000 cable runs, racking, 100 AP, 300 cameras, NVRs, controllers, and creating floor\nplans and topology documents.\nControlled a $2MM IT budget, short-term and long-term strategies, and CapEx justification across the business.\n\n\x0cIncluding selecting and negotiating with vendors, promoting operational process improvement, instituting best practices, and developing IT\nroadmaps and strategic plans.\nOn track to reduce IT spend by $250K by renegotiating vendor contracts, consolidating cloud services, implementing automation tools and\nupgrading legacy systems.\nResponsible for a team of IT professionals and vendors assigned to all corporate and local office systems, including ERP, WMS, logistics\nsystems, data centers, servers and storage, PCs, mobile devices, BDR, telecom, and help desk.\nReduced IT service desk's response time and resolution time while increasing knowledge base and reducing reoccurring tickets by over\n50%.\nInformation Technology Governance & Steering Committee (ITGSC) - Reporting directly to the board of directors, the ITGSC provided\nstrategic direction in aligning IT projects to shareholder interest and long-term targets.\nWhile overseeing the committee the cross-functional team guided 12 business units across operations, sales, and manufacturing.\nAdditionally, the ITGSC aided in risk management, business continuity, and organizational SOPs.\nNatJan Solutions (Facility Management - Retail, Medical, Grocery Sectors.\n\nInformation Technology and Analytics Manager , 01/2014 to 01/2017 \n\nImplemented process within external ERP portal to monetize 1000's of vendors to generate lean revenue based on financial and operational\ndata analysis.\nThis program is estimated to bring in $325,000 in its first year, an 8% increase in margin.\nCreated ad-hoc and scheduled BI (PowerBI/SSRS) reports to visualize critical client metrics and reports, internal performance KPIs,\noperational resource planning, asset and revenue forecasting, P/L summaries, expense budgets, etc.\nSpearheaded national RFP bids of multi-million-dollar procurement deals with several Fortune 500 retail, medical, and education\ncompanies.\nTasks included sales analysis, margin analysis, multivariable pricing structures, vendor acquisition, developing process flow and establishing\nKPI reporting for clientele and internal use.\nDesigned ad-hoc SQL views, stored procedures and reports to address company-wide data analysis and modeling.\nUtilized advanced VBA programming and automation software to manage two billing systems, saving an estimated $75,000 in Salary\nExpenses in 2015, translating to a 40% reduction in departmental spending.\nReported on a wide array of KPIs on operations, sales, accounting, and vendors via dashboard-style (BI/SSRS) reports for COO, CFO,\nVice President of Sales and Account Manager use.\nOverhauled all company technology from on-premise systems to an array of cloud solutions, including replacing hardware and migrating\nservers and databases, this renovation saves ~$108,000 per year and provides long-term scalability.\n\n01/2015 to 01/2017 \nCompany Name â€“ City , State \n\nCo-Founded indoor, hydroponic farming company in South Jersey.\nBringing a hyper-local product to the Camden and Philadelphia region HGF generated $100K in its first year via a strategic relationship with\nthe premier food management service in Philadelphia, local restaurants, farmer's markets, and Whole Foods retail chain.\nSales & Operations Planning (S&OP) - The S&OP team managed bi-directional interactions between sales, marketing, production, and\nfinance.\nS&OP committee oversaw finished goods inventory controls, marketing vs financial targets, raw material and supplier management, logistics\nand human capital planning.\nAdditionally, benchmarks for product mix, SKU management, and forecast vs demand vs actual alignment.\nOperations - Oversaw the general operations of the farm, including assigning day-to-day jobs, tracking yield results, establishing daily work\nschedules, and tracking transplanting/harvesting schedules.\nAutomation Systems - Implemented an array of sensors to control environmental and nutrient levels.\nUtilizing this data and automation systems we drove automated pH balancing, nutrient leveling, temperature control, ventilation systems, and\nestablished a strong exception-based manufacturing operation.\nFinance - Oversawall aspects of the financial responsibilities including establishing a point of sales systems, P/L reports, budgeting for OpEx\nand CapEx schedules, coordinating with lenders, insurance institutions and annual tax reports.\nSOPs - Instituted standard operating procedures to ensure quality standards are maintained and product consistency is maintained.\n\nEducation\nBachelor of Science : Management of Information Systems , 2017 \nAssociates of Science : Accounting , 2015 \nRowan College \nPursuing Project Management Professional (PMP) certification Rowan University \nSummary\nZeel Patel is an Information Technology Manager with a focus on IT transformation and process improvement currently looking for opportunities in\nthe greater Miami, FL metropolitan area. Zeel has experience working with corporate data in the areas of data presentation, structured and\nunsecured datasets, data mining, statistical analysis, UI creation, data warehouse management, and assessing data quality. Additionally, Zeel's\ndiverse background has allowed him to succeed in a project management and IT management role. In this role, Zeel has engaged in holistic\nbusiness analysis, process improvement, strategic planning, budgeting, contract negotiations, vendor relations, resource management, instituting\nbest practices, and overseeing/implementing multiple enterprise systems (ERP, WMS, CRM, WOM, QMS, SCP).\nHighlights\n\nAutomation tools, HTML, Retail\n\n\x0cMicrosoft Office Suite with deep Office 365, Dynamics 365, Project, PowerApps, PowerBI,\nFlow,\nSharepoint, Excel, Access, Intune, Visio, EMS, and Azure proficiency\nProgramming/Databases: SQL (SSRS, SSIS, SSAS), VBA, DAX, HTML, CSS, VBA,\nVB.NET, R, Powershell, Python, Oracle\nBusiness Intelligence Packages: PowerBI, Qlik (QlikView/QlikSense), SiSense, Tableau,\nDatorama, Yellowfin, Crystal, SSRS\nStrong knowledge of AWS, Azure, Cisco Switch Management, VMWare, Hyper-V, RDP,\nAutomation Anywhere, Active Directory,\nAnd hardware and software administration for iOS, Android, Windows, Red Hat Linux, RF\ndevices\nVB.NET, EDI, Procurement, Ventilation\nAccounting, ERP, Programming, Visio\nActive Directory, ETL, Progress, VBA\nPremier, Facility Management, Project Management, Workflow\nAd, Finance, Python\nAP, Financial, Quality\nApproach, Floor plans, Real-time\nArchitect, Forecasting, Red Hat Linux\nAutomate, Functional, Renovation\nAutomation, Help desk, Reporting\n\nAutomation tools, HTML, Retail\nBilling systems, Information\nTechnology, RFP\nBudgeting, Insurance, Risk\nmanagement\nBudgets, Inventory, Sales\nBudget, Logic, Sales analysis\nBI, Logistics, Servers\nBusiness Intelligence, Marketing,\nSOP\nCable, Access, SQL\nCisco, Excel, Strategy\nHardware, Exchange, Strategic\nContracts, Microsoft Office Suite,\nStrategic plans\nCrystal, Office, Structured\nCSS, Sharepoint, Supplier\nmanagement\nClientele, Windows, Supply chain\nClient, Negotiating, Supply Chain\nManagement\nClients, Enterprise, Switches\nData analysis, Network, Switch\nData entry, Oracle, System\nintegration\nData analysis and modeling, Oracle\ndatabase, Tableau\nData warehouses, Organizational,\nTax\nDatabases, Cameras, User training\nData Warehousing, Policies,\nTelecom\nDirection, Pricing, Translating\nDocumentation, Process\nimprovement, Upgrading\n\nSkills\n\nMicrosoft Office Suite with deep Office 365, Dynamics 365, Project, PowerApps, PowerBI, Flow,\nSSharepoint, Excel, Access, Intune, Visio, EMS, and Azure proficiency\nPProgramming/Databases: SQL (SSRS, SSIS, SSAS), VBA, DAX, HTML, CSS, VBA, VB.NET, R, Powershell, Python, Oracle\nBBusiness Intelligence Packages: PowerBI, Qlik (QlikView/QlikSense), SiSense, Tableau, Datorama, Yellowfin, Crystal, SSRS\nSStrong knowledge of AWS, Azure, Cisco Switch Management, VMWare, Hyper-V, RDP, Automation Anywhere, Active Directory,\nAand hardware and software administration for iOS, Android, Windows, Red Hat Linux, RF devices,\nVB.NET, accounting, Active Directory, premier, ad, AP, approach, architect, Automate, Automation, automation tools, billing systems,\n\nbudgeting, budgets, budget, BI, Business Intelligence, cable, Cisco, hardware, contracts, Crystal, CSS, clientele, client, clients, data analysis, data\nentry, data analysis and modeling, data warehouses, Databases, Data Warehousing, direction, documentation, EDI, ERP, ETL, Facility\nManagement, Finance, financial, floor plans, forecasting, functional, help desk, HTML, Information Technology, insurance, inventory, logic,\nlogistics, marketing, Access, Excel, exchange, Microsoft Office Suite, Office, Sharepoint, Windows, negotiating, enterprise, network, Oracle,\nOracle database, organizational, cameras, policies, pricing, process improvement, procurement, Programming, progress, Project Management,\nPython, Quality,